const now = new Date();

const daysAgo = (days, hours = 0) => {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  date.setHours(9 + hours, 15, 0, 0);
  return date.toISOString();
};

export const seedCategories = [
  {
    id: 'cat-geral',
    nome: 'Geral',
    slug: 'geral',
    descricao: 'Informes gerais da organização',
    ativa: true,
    criadoEm: daysAgo(40),
  },
  {
    id: 'cat-assembleias',
    nome: 'Assembleias',
    slug: 'assembleias',
    descricao: 'Convocações e resultados das assembleias',
    ativa: true,
    criadoEm: daysAgo(35),
  },
  {
    id: 'cat-atas',
    nome: 'Atas',
    slug: 'atas',
    descricao: 'Atas de reuniões oficiais',
    ativa: true,
    criadoEm: daysAgo(35),
  },
  {
    id: 'cat-comunicados-tjd',
    nome: 'Comunicados TJD',
    slug: 'comunicados-tjd',
    descricao: 'Publicações oficiais do Tribunal de Justiça Desportiva',
    ativa: true,
    criadoEm: daysAgo(35),
  },
];

export const seedUsers = [
  {
    id: 'user-admin',
    nome: 'Ana Administradora',
    email: 'admin@organizacao.local',
    role: 'admin',
    senha: '123456',
  },
  {
    id: 'user-secretaria',
    nome: 'Sergio Secretaria',
    email: 'secretaria@organizacao.local',
    role: 'secretaria',
    senha: '123456',
  },
  {
    id: 'user-tjd',
    nome: 'Teresa TJD',
    email: 'tjd@organizacao.local',
    role: 'tjd',
    senha: '123456',
    allowedCategorySlugs: ['comunicados-tjd'],
  },
  {
    id: 'user-editor',
    nome: 'Edu Editor',
    email: 'editor@organizacao.local',
    role: 'editor',
    senha: '123456',
    allowedCategorySlugs: ['geral', 'atas'],
  },
  {
    id: 'user-leitor',
    nome: 'Lia Leitor',
    email: 'leitor@organizacao.local',
    role: 'leitor',
    senha: '123456',
  },
];

export const seedPosts = [
  {
    id: 'post-001',
    titulo: 'Assembleia Geral Extraordinária',
    slug: 'assembleia-geral-extraordinaria',
    resumo: 'Convocação para a Assembleia Geral Extraordinária do próximo mês.',
    conteudoMarkdown:
      '# Assembleia Geral Extraordinária\n\nA assembleia acontecerá no auditório principal...\n\n- Data: 22/09\n- Horário: 19h',
    capaUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=60',
    categoriaId: 'cat-assembleias',
    categoriaNome: 'Assembleias',
    status: 'publicado',
    publicadoEm: daysAgo(2),
    autorId: 'user-secretaria',
    autorNome: 'Sergio Secretaria',
    criadoEm: daysAgo(10),
    atualizadoEm: daysAgo(2),
    destaque: true,
  },
  {
    id: 'post-002',
    titulo: 'Relatório da última assembleia',
    slug: 'relatorio-ultima-assembleia',
    resumo: 'Resumo das decisões aprovadas na assembleia do dia 10.',
    conteudoMarkdown: '## Principais decisões\n\n1. Aprovação das contas\n2. Calendário da temporada',
    categoriaId: 'cat-assembleias',
    categoriaNome: 'Assembleias',
    status: 'publicado',
    publicadoEm: daysAgo(6),
    autorId: 'user-admin',
    autorNome: 'Ana Administradora',
    criadoEm: daysAgo(15),
    atualizadoEm: daysAgo(6),
  },
  {
    id: 'post-003',
    titulo: 'Boletim Geral Semanal',
    slug: 'boletim-geral-semanal',
    resumo: 'Comunicações gerais da semana, incluindo agenda e destaque esportivo.',
    conteudoMarkdown:
      '### Agenda da semana\n\n- Treinos\n- Eventos\n- Reuniões',
    categoriaId: 'cat-geral',
    categoriaNome: 'Geral',
    status: 'publicado',
    publicadoEm: daysAgo(4),
    autorId: 'user-secretaria',
    autorNome: 'Sergio Secretaria',
    criadoEm: daysAgo(12),
    atualizadoEm: daysAgo(4),
  },
  {
    id: 'post-004',
    titulo: 'Ata da reunião de diretoria',
    slug: 'ata-reuniao-diretoria-ago',
    resumo: 'Disponibilizamos a ata da reunião realizada em 05/09.',
    conteudoMarkdown: 'Documento completo disponível para download interno.',
    categoriaId: 'cat-atas',
    categoriaNome: 'Atas',
    status: 'publicado',
    publicadoEm: daysAgo(9),
    autorId: 'user-editor',
    autorNome: 'Edu Editor',
    criadoEm: daysAgo(20),
    atualizadoEm: daysAgo(9),
  },
  {
    id: 'post-005',
    titulo: 'Comunicado TJD - Suspensão preventiva',
    slug: 'comunicado-tjd-suspensao-preventiva',
    resumo: 'TJD informa suspensão preventiva de atleta até julgamento.',
    conteudoMarkdown:
      'O Tribunal de Justiça Desportiva comunicou na data de hoje a suspensão preventiva...',
    categoriaId: 'cat-comunicados-tjd',
    categoriaNome: 'Comunicados TJD',
    status: 'publicado',
    publicadoEm: daysAgo(1),
    autorId: 'user-tjd',
    autorNome: 'Teresa TJD',
    criadoEm: daysAgo(3),
    atualizadoEm: daysAgo(1),
  },
  {
    id: 'post-006',
    titulo: 'Calendário oficial de competições',
    slug: 'calendario-oficial-competicoes',
    resumo: 'Confira o calendário atualizado de competições da temporada.',
    conteudoMarkdown: 'Calendário detalhado disponível para download.',
    categoriaId: 'cat-geral',
    categoriaNome: 'Geral',
    status: 'publicado',
    publicadoEm: daysAgo(8),
    autorId: 'user-admin',
    autorNome: 'Ana Administradora',
    criadoEm: daysAgo(18),
    atualizadoEm: daysAgo(8),
  },
  {
    id: 'post-007',
    titulo: 'Regulamento atualizado do campeonato',
    slug: 'regulamento-atualizado-campeonato',
    resumo: 'Documento com as principais alterações do regulamento.',
    conteudoMarkdown: 'Confira os artigos atualizados no anexo.',
    categoriaId: 'cat-atas',
    categoriaNome: 'Atas',
    status: 'publicado',
    publicadoEm: daysAgo(11),
    autorId: 'user-editor',
    autorNome: 'Edu Editor',
    criadoEm: daysAgo(22),
    atualizadoEm: daysAgo(11),
  },
  {
    id: 'post-008',
    titulo: 'Credenciamento de imprensa aberto',
    slug: 'credenciamento-imprensa-aberto',
    resumo: 'Profissionais de imprensa podem solicitar credenciamento até 25/09.',
    conteudoMarkdown: 'Solicite pelo e-mail comunicacao@organizacao.local.',
    categoriaId: 'cat-geral',
    categoriaNome: 'Geral',
    status: 'publicado',
    publicadoEm: daysAgo(5),
    autorId: 'user-secretaria',
    autorNome: 'Sergio Secretaria',
    criadoEm: daysAgo(14),
    atualizadoEm: daysAgo(5),
  },
  {
    id: 'post-009',
    titulo: 'Nota oficial sobre julgamento TJD',
    slug: 'nota-oficial-julgamento-tjd',
    resumo: 'O TJD marcou julgamento para o dia 02/10.',
    conteudoMarkdown: 'Detalhes adicionais serão publicados após o julgamento.',
    categoriaId: 'cat-comunicados-tjd',
    categoriaNome: 'Comunicados TJD',
    status: 'agendado',
    publicadoEm: daysAgo(-3),
    autorId: 'user-tjd',
    autorNome: 'Teresa TJD',
    criadoEm: daysAgo(1),
    atualizadoEm: daysAgo(0),
  },
  {
    id: 'post-010',
    titulo: 'Planejamento estratégico 2025',
    slug: 'planejamento-estrategico-2025',
    resumo: 'Documento em elaboração com diretrizes para 2025.',
    conteudoMarkdown: 'Versão preliminar em revisão pela diretoria.',
    categoriaId: 'cat-geral',
    categoriaNome: 'Geral',
    status: 'rascunho',
    criadoEm: daysAgo(5),
    atualizadoEm: daysAgo(2),
    autorId: 'user-admin',
    autorNome: 'Ana Administradora',
  },
  {
    id: 'post-011',
    titulo: 'Ata reunião comissão técnica',
    slug: 'ata-reuniao-comissao-tecnica',
    resumo: 'Reunião da comissão técnica realizada em 19/09.',
    conteudoMarkdown: 'Conteúdo em revisão.',
    categoriaId: 'cat-atas',
    categoriaNome: 'Atas',
    status: 'rascunho',
    criadoEm: daysAgo(4),
    atualizadoEm: daysAgo(1),
    autorId: 'user-editor',
    autorNome: 'Edu Editor',
  },
  {
    id: 'post-012',
    titulo: 'Informe financeiro trimestral',
    slug: 'informe-financeiro-trimestral',
    resumo: 'Prestação de contas referente ao 2º trimestre.',
    conteudoMarkdown: 'Documento será publicado após aprovação.',
    categoriaId: 'cat-geral',
    categoriaNome: 'Geral',
    status: 'rascunho',
    criadoEm: daysAgo(3),
    atualizadoEm: daysAgo(1),
    autorId: 'user-secretaria',
    autorNome: 'Sergio Secretaria',
  },
];
